### ISSUE TITLE
Target temperature missing

### ISSUE THREAD

**Issue by FransHalsjes** [minzel/home-assistant-miele#2]
does not work at all. Miele equipment is not seen as entities or sensors.

**Comment by minzel** [comment]
Hello, thanks for your feedback.

Do you have any logs and which kind of device do you use?

The json would be helpful: https://www.miele.com/developer/swagger-ui/swagger.html#/Information/get_devices

If you don't want it to be public you can send the json data via my email.

**Comment by FransHalsjes** [comment]
Hi Frank,

Thanks for your quick response. I have here an Oven, Combi steam Oven,
warming drawer and CookTop. json is attached.

I had an old integration running (
https://github.com/HomeAssistant-Mods/home-assistant-miele). that worked (I
saw all the applicances as sensors and could control them via services.
However, the integration gave a lot of Assertion errors. Therefore I
deleted this one, removed the mile token and installed yours through HACS.
However, no appliances appear.So, i removed your integration and
re-installed the original one.

Looking forward to hear from you,

If I can help testing your integration, let me know,

Greetings,

Op ma 2 nov. 2020 om 10:22 schreef Frank Gottschlich <
notifications@github.com>:

**Comment by minzel** [comment]
I can't find the cooktop.json file. Where did you attach it to?

**Comment by FransHalsjes** [comment]
hmmm.. i thought i attached it to the mail. another attempt...

Op di 3 nov. 2020 om 11:50 schreef Frank Gottschlich <
notifications@github.com>:

**Comment by FransHalsjes** [comment]
ah! the file is called response_1604311500037.json , not cooktop. json
---------- Forwarded message ---------
Van: Frans Halsjes <franshalsjes@gmail.com>
Date: di 3 nov. 2020 om 12:25
Subject: Re: [minzel/home-assistant-miele] does not work (#2)
To: minzel/home-assistant-miele <
reply@reply.github.com>


hmmm.. i thought i attached it to the mail. another attempt...

Op di 3 nov. 2020 om 11:50 schreef Frank Gottschlich <
notifications@github.com>:

**Comment by minzel** [comment]
Hello FransHalsjes,

I think, files must be attach directly to github comments (https://github.blog/2015-09-25-attach-files-to-comments/). Email attachments doesn't seem to work.

You can send me the json directly to f.gottschlich@gmail.com

**Comment by FransHalsjes** [comment]
ok! will do!

Op wo 4 nov. 2020 om 00:49 schreef Frank Gottschlich <
notifications@github.com>:

**Comment by minzel** [comment]
I got the file. I will look into it.

**Comment by minzel** [comment]
The master-Branch contains a fix. Your json will be parse correctly now, but there could be other constellations that do not work properly yet.

**Comment by FransHalsjes** [comment]
Hi Frank,

I have re-installed your app, but the miele entities still do not appear.
What can i get you to help debug?

Greetings,

Frans

Op za 7 nov. 2020 om 17:24 schreef Frank Gottschlich <
notifications@github.com>:

**Comment by FransHalsjes** [comment]
to add to the previous message. This morning I restarted Home Assistant and
got the following error:
2020-11-08 09:47:03 ERROR (MainThread) [homeassistant.config_entries] Error
setting up entry Configuration.yaml for miele
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in
async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/miele/__init__.py", line 94, in
async_setup_entry
await update_all_devices(hass)
File "/config/custom_components/miele/__init__.py", line 121, in
update_all_devices
data[DEVICES] = await hass.async_add_executor_job(data[API].get_devices,
config.get(CONF_LANGUAGE))
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in
run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/miele/miele_api.py", line 43, in get_devices
return [Device(k, **d) for k, d in r.json().items()]
File "/config/custom_components/miele/miele_api.py", line 43, in <listcomp>
return [Device(k, **d) for k, d in r.json().items()]
File "/config/custom_components/miele/model.py", line 333, in __init__
self.state = State(self.ident.type.value_raw, **state)
File "/config/custom_components/miele/model.py", line 286, in __init__
temperature = (int)(targetTemperatures[i].value_localized)
TypeError: int() argument must be a string, a bytes-like object or a
number, not 'NoneType'

configuration.yaml contained:
language: en
when not using the language switch i get the same error.


Op za 7 nov. 2020 om 23:10 schreef Frans Halsjes <franshalsjes@gmail.com>:

**Comment by minzel** [comment]
Hello FransHalsjes,

thanks for your feedback. This does not seem to be the current code from master-Branch.

I have created a bugfix version 1.0.3. You can download and install in HACS directly. After update, you should reboot your HA instance to reinit the component.

**Comment by FransHalsjes** [comment]
yep! that worked. thank you very much.

Do you also (plan to) provide the capability to control the miele
equipment? (start oven, set temperature, etc..)?
The miele API offers these functionalities:
https://www.miele.com/developer/swagger-ui/swagger.html#/Action/put_devices__deviceId__actions

looking forward to hear from you.

Have a great sunday!

Frans

Op zo 8 nov. 2020 om 10:51 schreef Frank Gottschlich <
notifications@github.com>:

**Comment by FransHalsjes** [comment]
Hi Frank,

I have been experimenting with your app. For my oven and Steam oven I am
missing the sensors for temperature and target temperature. Can you add
them to the integration. (a JSON return from the miele API is below.

Thanks

Frans

{
  "ident": {
    "type": {
      "key_localized": "Devicetype",
      "value_raw": 12,
      "value_localized": "Oven"
    },
    "deviceName": "",
    "deviceIdentLabel": {
      "fabNumber": "000138017784",
      "fabIndex": "00",
      "techType": "H7860BP",
      "matNumber": "11101630",
      "swids": [
        "4855",
        "4859",
        "25211",
        "25210",
        "4860",
        "25245",
        "4880",
        "4857",
        "25300",
        "25307",
        "25247",
        "20436",
        "25223",
        "4874",
        "20366",
        "20462"
      ]
    },
    "xkmIdentLabel": {
      "techType": "EK037",
      "releaseVersion": "03.85"
    }
  },
  "state": {
    "ProgramID": {
      "value_raw": 13,
      "value_localized": "Convection Broil",
      "key_localized": "Program Id"
    },
    "status": {
      "value_raw": 7,
      "value_localized": "Finished",
      "key_localized": "State"
    },
    "programType": {
      "value_raw": 1,
      "value_localized": "Own program",
      "key_localized": "Program type"
    },
    "programPhase": {
      "value_raw": 3078,
      "value_localized": "Program Finished",
      "key_localized": "Phase"
    },
    "remainingTime": [
      0,
      0
    ],
    "startTime": [
      0,
      0
    ],
    "targetTemperature": [
      {
        "value_raw": 16000,
        "value_localized": 160,
        "unit": "Celsius"
      },
      {
        "value_raw": -32768,
        "value_localized": null,
        "unit": "Celsius"
      },
      {
        "value_raw": -32768,
        "value_localized": null,
        "unit": "Celsius"
      }
    ],
    "temperature": [
      {
        "value_raw": 7708,
        "value_localized": 77.08,
        "unit": "Celsius"
      },
      {
        "value_raw": -32768,
        "value_localized": null,
        "unit": "Celsius"
      },
      {
        "value_raw": -32768,
        "value_localized": null,
        "unit": "Celsius"
      }
    ],
    "signalInfo": false,
    "signalFailure": false,
    "signalDoor": false,
    "remoteEnable": {
      "fullRemoteControl": true,
      "smartGrid": false,
      "mobileStart": true
    },
    "light": 2,
    "elapsedTime": [
      0,
      33
    ],
    "spinningSpeed": {
      "unit": "rpm",
      "value_raw": null,
      "value_localized": null,
      "key_localized": "Spinning Speed"
    },
    "dryingStep": {
      "value_raw": null,
      "value_localized": "",
      "key_localized": "Drying level"
    },
    "ventilationStep": {
      "value_raw": null,
      "value_localized": "",
      "key_localized": "Power Level"
    },
    "plateStep": [],
    "ecoFeedback": null
  }}


Op zo 8 nov. 2020 om 11:28 schreef Frans Halsjes <franshalsjes@gmail.com>:

**Comment by minzel** [comment]
Should be resolved in #3
